config/routes.rb
Social::Application.routes.draw do

  get "gist/index"

  get "gist/new"

  get "gist/edit"

  get "gist/show"

  get "friend/index"

  get "friend/search"

  get "admin/index"

  root :to => 'topics#index'

  match  'node/new/:node' => 'topics#new', :as => :new_topic
  get  'node/:node' => "topics#node", :as => :node

  match  't/:id/edit' => 'topics#edit', :as => :edit_topic
  post 't/:id/reply' => 'topics#reply', :as => :reply
  post 't/:id/fav' => 'topics#fav', :as => :fav
  post 't/:id/unfav' => 'topics#unfav', :as => :unfav
  post 't/:id/like' => 'topics#like', :as => :like
  post 't/:id/dislike' => 'topics#dislike', :as => :dislike
  post 't/:id/ban' => 'topics#ban', :as => :ban
  get  't/:id' => 'topics#show', :as => :topic

  post 'r/:id/like' => 'topics#reply_like', :as => :reply_like
  post 'r/:id/dislike' => 'topics#reply_dislike', :as => :reply_dislike

  get  'news' => "news#index", :as => :all_news
  match  'news/new' => 'news#new', :as => :new_news
  match  'news/:id/edit' => 'news#edit', :as => :edit_news
  post 'news/:id/reply' => 'news#reply', :as => :reply_news
  get  'news/:id' => 'news#show', :as => :news
  
  get  'page' => "page#index", :as => :pages
  match  'page/new' => 'page#new', :as => :new_page
  match  'page/:id/edit' => 'page#edit', :as => :edit_page
  post 'gist/:id/reply' => 'gist#reply', :as => :reply_gist
  get  'page/:id' => 'page#show', :as => :page

  get  'gist' => "gist#index", :as => :gists
  match  'gist/new' => 'gist#new', :as => :new_gist
  match  'gist/:id/edit' => 'gist#edit', :as => :edit_gist
  get  'gist/:id' => 'gist#show', :as => :gist

  get  'asks' => "ask#index", :as => :asks
  match  'ask/new' => 'ask#new', :as => :new_ask
  get  'ask/node/:node' => "ask#node", :as => :ask_node
  match  'ask/:id/edit' => 'ask#edit', :as => :edit_ask
  post 'ask/:id/answer' => 'ask#answer', :as => :answer
  post 'ask/:id/fav' => 'ask#fav', :as => :fav_ask
  post 'ask/:id/unfav' => 'ask#unfav', :as => :unfav_ask
  post 'ask/:id/like' => 'ask#like', :as => :like_answer
  post 'ask/:id/dislike' => 'ask#dislike', :as => :dislike_answer
  get  'ask/:id' => 'ask#show', :as => :ask

  get  'friend/(:user)' => "friend#index", :as => :friends
  get  'friend/search/:user' => "friend#search", :as => :search_friends
  post 'friend/:id/follow' => 'friend#follow', :as => :follow_friend
  post 'friend/:id/unfollow' => 'friend#unfollow', :as => :unfollow_friend
  post 'friend/:id/block' => 'friend#block', :as => :block_friend
  post 'friend/:id/unblock' => 'friend#unblock', :as => :unblock_friend

  get  'share' => "share#index", :as => :shares
  match  'share/new/:node' => 'share#new', :as => :new_share
  get  'share/node/:node' => "share#node", :as => :share_node
  match  'share/:id/edit' => 'share#edit', :as => :edit_share
  post 'share/:id/reply' => 'share#reply', :as => :reply_share
  get  'share/:id' => 'share#show', :as => :share

  get  'users' => 'users#index', :as => :users
  get  'users/city/:city' => 'users#city', :as => :users_by_city
  match  'u/setting' => 'users#setting', :as => :user_setting
  match  'u/avatar' => 'users#avatar', :as => :user_avatar
  get  'u/:id/topics' => 'users#topics', :as => :user_topics
  get  'u/:id/replies' => 'users#replies', :as => :user_replies
  get  'u/:id/favs' => 'users#favs', :as => :user_favs
  get  'u/:id' => 'users#show', :as => :user

  match 'signup_by_weibo' => 'users#signup_by_weibo' , :as => :signup_by_weibo

  devise_for :users ,controllers:{omniauth_callbacks: :authentications}

  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'change_pwd' => 'users#change_pwd', :as => :change_pwd
  match 'forgot_pwd' => 'users#forgot_pwd', :as => :forgot_pwd

end

app/controllers/ask_controller.rb
class AskController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:index, :show]

  def index
    @questions = Question.where(:state => :normal).all
  end

  def new
    if request.post?
      @question = Question.create(params[:question])
      @question.user = current_user
      @question.state = 'normal'
      @question.save
      redirect_to ask_path(@question)
    else
      @question = Question.new
    end
  end

  def edit
    @question = Question.find(params[:id])
    if request.post?
      @question.update_attributes(params[:question])
      redirect_to ask_path(@question)
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.user == current_user
      @question.state = 'destroyed' 
      @question.save
    end
  end

  def answer
    if request.post?
      @question = Question.find(params[:id])

      @answer = Answer.new
      @answer.question_id = @question.id
      @answer.user = current_user
      @answer.floor = @question.answers.count + 1
      @answer.content = params[:content]
      @answer.save

      puts ask_path(@question)
      redirect_to ask_path(@question)
    end
  end

  def reply
    @question = Question.find(params[:id])

    @reply = Reply.new
    @reply.repliable = @question
    @reply.user = @user
    @reply.content = params[:content]
    @reply.save

    redirect_to ask_path(@question)
  end

  def fav
    @question = Question.find(params[:id])

    favorite = Fav.new
    favorite.share_id = @question.id
    favorite.user_id = current_user.id
    favorite.save

    render :status => 200
  end

  def unfav
    @question = Question.find(params[:id])

    favorite = Fav.where(:user_id => current_user.id, :share_id => @question.id).first
    favorite.delete
    render :status => 200
  end

  def up
    @answer = Answer.find(params[:answer_id])
    @answer.rate += 5
    @answer.save
    
    render :status => 200
  end

  def down
    @answer = Answer.find(params[:answer_id])
    @answer.rate -= 5
    @answer.save
    
    render :status => 200
  end

  def select
  	@question = Question.find(params[:id])
    @answer = Answer.find(params[:answer_id])
    @question.selected = @answer
    @question.state = :closed
    @question.save

    redirect_to ask_path(@question)
  end

  def ban
    if @user.blank? || @user.state != 'admin'
      redirect_to '/'
      return
    end

    @question = Question.find(params[:share_id])
    @question.state = 'ban'
    @question.save

    render :status => 200
  end
end

app/helpers/ask_helper.rb
module AskHelper
end

app/views/ask/_answer.html.erb
<!-- nice -->
<% if user_signed_in? %>
<div class="topic-reply-create container-box">
<div class="ui-header">
  <span class="title">创建新的回复</span>
</div>
<div class="ui-content">
  <%= form_for(@answer, :class => 'mt10', :url => url, :method => :post) do |f| %>
    <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '回复内容' %>
    <%= hidden_field_tag(owner_name, owner) %>
    <%= f.submit "立即回复", :class => 'btn btn-small' %>
  <% end %>
</div>
</div>
<% end %>

app/views/ask/_answers.html.erb
<!-- nice -->
<% answers.each do |answer| %>
<div class="reply-item">
  <%= link_to image_tag(answer.user.avatar, :class => 'avatar'), user_path(answer.user) %>
  <div class="main">
    <div class="meta">
      <a href="<%= user_path(answer.user) %>" class="reply-username">
        <span class="username"><%= answer.user.username %></span>
      </a>
      <span class="time"><%= time_ago_in_words answer.created_at %></span>
      <a href="<%= reply_like_path(answer.id) %>" class="J_topicVote">感谢</a>
      <span class="floor fr">#<%= answer.floor %></span>
      <span class="reply-to fr J_replyTo" data-username="<%= answer.user.username %>">
        <img src="/reply.png" alt="">
      </span>
    </div>
    <span class="content"><p><%= answer.content %></p></span>
  </div>
</div>
<% end %>

app/views/ask/edit.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">编辑</span>
    </div>
    <div class="ui-content">
        <%= form_for(@question, :class => 'mt10', :url => edit_ask_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/ask/index.html.erb
<div class="topics container-box">
  <div class="ui-header">
    <%= link_to '创建新主题', new_ask_path, :class => 'btn btn-small fr' %>
    <span class="bread-nav"> 问答 </span>
  </div>

  <% @questions.each do |question| %>
  <div class="topic-item">

    <div class="main">
      <h3 class="title">
        <%= link_to question.title, ask_path(question.id) %>
      </h3>

      <div class="ui-content">
        <p><%= question.content %></p>
      </div>

      <div class="meta">
        <span class="username">
          <%= link_to question.user.username, user_path(question.user)  %>
        </span> •
        <span class="last-touched"><%= time_ago_in_words question.created_at %></span> •
      </div>
    </div>
    <div class="count">
      <%= link_to question.answers.count, ask_path(question.id) %>
    </div>
  </div>
  <% end %>
</div>

app/views/ask/new.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">发表</span>
    </div>
    <div class="ui-content">
        <%= form_for(@question, :class => 'mt10', :url => new_ask_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/ask/show.html.erb
<div class="topic-detail container-box">
<div class="ui-header">
    <%= link_to image_tag(@question.user.avatar, :class => 'avatar'), user_path(@question.user) %>
    <div class="main">
        <h3 class="title"><%= @question.title %></h3>
        <div class="meta">
            <span class="node"><%= link_to 'all', node_path('all') %></span>
            • <span class="username"><%= link_to @question.user.username, user_path(@question.user.username) %></span>
            • <span class="created-time"><%= time_ago_in_words @question.created_at %></span>
        </div>
    </div>
</div>
<div class="ui-content">
    <p><%= @question.content %></p>
</div>
<div class="ui-footer">
    <%= link_to '编辑', edit_ask_path(@question.id), :class => 'J_topicVote' %>
    <%= link_to '收藏', fav_path(@question.id), :class => 'J_topicVote' %>
    <%= link_to '喜欢', like_path(@question.id), :class => 'J_topicVote' %>
    <%= link_to '不喜欢', dislike_path(@question.id), :class => 'J_topicVote' %>
    <% if @user && @user.state = 'admin' %>
    <%= link_to '屏蔽', ban_path(@question.id), :class => 'J_topicVote' %>
    <% end %>
    <span class="hits fr mr10"><%= @question.page_view %> 次点击</span>
</div>
</div>
<div class="topic-reply container-box">
<div class="ui-header">
    <span>共收到<%= @question.answers.count %>条回复</span>
</div>
<div class="ui-content">
    <%= render :partial => 'answers', :locals => {:answers => @question.answers} %>
</div>
<div class="ui-footer">
    <div class="pagination pagination-mini"></div>
</div>
</div>


<%= render :partial => 'answer', :locals => {:url => answer_path(@question), :owner_name => :question_id, :owner => @question.id} %>