config/routes.rb
Social::Application.routes.draw do

  get "gist/index"

  get "gist/new"

  get "gist/edit"

  get "gist/show"

  get "friend/index"

  get "friend/search"

  get "admin/index"

  root :to => 'topics#index'

  match  'node/new/:node' => 'topics#new', :as => :new_topic
  get  'node/:node' => "topics#node", :as => :node

  match  't/:id/edit' => 'topics#edit', :as => :edit_topic
  post 't/:id/reply' => 'topics#reply', :as => :reply
  post 't/:id/fav' => 'topics#fav', :as => :fav
  post 't/:id/unfav' => 'topics#unfav', :as => :unfav
  post 't/:id/like' => 'topics#like', :as => :like
  post 't/:id/dislike' => 'topics#dislike', :as => :dislike
  post 't/:id/ban' => 'topics#ban', :as => :ban
  get  't/:id' => 'topics#show', :as => :topic

  post 'r/:id/like' => 'topics#reply_like', :as => :reply_like
  post 'r/:id/dislike' => 'topics#reply_dislike', :as => :reply_dislike

  get  'news' => "news#index", :as => :all_news
  match  'news/new' => 'news#new', :as => :new_news
  match  'news/:id/edit' => 'news#edit', :as => :edit_news
  post 'news/:id/reply' => 'news#reply', :as => :reply_news
  get  'news/:id' => 'news#show', :as => :news
  
  get  'page' => "page#index", :as => :pages
  match  'page/new' => 'page#new', :as => :new_page
  match  'page/:id/edit' => 'page#edit', :as => :edit_page
  post 'gist/:id/reply' => 'gist#reply', :as => :reply_gist
  get  'page/:id' => 'page#show', :as => :page

  get  'gist' => "gist#index", :as => :gists
  match  'gist/new' => 'gist#new', :as => :new_gist
  match  'gist/:id/edit' => 'gist#edit', :as => :edit_gist
  get  'gist/:id' => 'gist#show', :as => :gist

  get  'asks' => "ask#index", :as => :asks
  match  'ask/new' => 'ask#new', :as => :new_ask
  get  'ask/node/:node' => "ask#node", :as => :ask_node
  match  'ask/:id/edit' => 'ask#edit', :as => :edit_ask
  post 'ask/:id/answer' => 'ask#answer', :as => :answer
  post 'ask/:id/fav' => 'ask#fav', :as => :fav_ask
  post 'ask/:id/unfav' => 'ask#unfav', :as => :unfav_ask
  post 'ask/:id/like' => 'ask#like', :as => :like_answer
  post 'ask/:id/dislike' => 'ask#dislike', :as => :dislike_answer
  get  'ask/:id' => 'ask#show', :as => :ask

  get  'friend/(:user)' => "friend#index", :as => :friends
  get  'friend/search/:user' => "friend#search", :as => :search_friends
  post 'friend/:id/follow' => 'friend#follow', :as => :follow_friend
  post 'friend/:id/unfollow' => 'friend#unfollow', :as => :unfollow_friend
  post 'friend/:id/block' => 'friend#block', :as => :block_friend
  post 'friend/:id/unblock' => 'friend#unblock', :as => :unblock_friend

  get  'share' => "share#index", :as => :shares
  match  'share/new/:node' => 'share#new', :as => :new_share
  get  'share/node/:node' => "share#node", :as => :share_node
  match  'share/:id/edit' => 'share#edit', :as => :edit_share
  post 'share/:id/reply' => 'share#reply', :as => :reply_share
  get  'share/:id' => 'share#show', :as => :share

  get  'users' => 'users#index', :as => :users
  get  'users/city/:city' => 'users#city', :as => :users_by_city
  match  'u/setting' => 'users#setting', :as => :user_setting
  match  'u/avatar' => 'users#avatar', :as => :user_avatar
  get  'u/:id/topics' => 'users#topics', :as => :user_topics
  get  'u/:id/replies' => 'users#replies', :as => :user_replies
  get  'u/:id/favs' => 'users#favs', :as => :user_favs
  get  'u/:id' => 'users#show', :as => :user

  match 'signup_by_weibo' => 'users#signup_by_weibo' , :as => :signup_by_weibo

  devise_for :users ,controllers:{omniauth_callbacks: :authentications}

  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'change_pwd' => 'users#change_pwd', :as => :change_pwd
  match 'forgot_pwd' => 'users#forgot_pwd', :as => :forgot_pwd

end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :content, :last_reply_id, :last_reply_user_name, :node,
   :page_view, :replied_at, :rate, :state, :tags, :title, :user_id,
   :download_count, :file
   has_many :replies, :as => :repliable
   belongs_to :user
   has_attached_file :file
end

app/controllers/share_controller.rb
class ShareController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:search, :index, :node, :show]

  def search
  end

  def index
    @shares = Share.where(:state => :normal).all
  end

  def node
    @nodename = params[:node]
    @shares = Share.where(:node => @nodename, :state => :normal)
  end

  def new
    @nodename = params[:node]
    if request.post?
      @share = Share.create(params[:share])
      @share.node = @nodename
      @share.state = 'normal'
      @share.user = current_user
      @share.save
      redirect_to share_path(@share)
    else
      @share = Share.new
    end
  end

  def edit
    @share = Share.find(params[:id])
    if request.post?
      @share.update_attributes(params[:share])
      @share.save
      redirect_to share_path(@share)
    end
  end

  def show
    @share = Share.find(params[:id])
    @replies = @share.replies
    @reply = Reply.new
  end

  def destroy
    @share = Share.find(params[:id])
    if @share.user == @user
      @share.state = 'destroyed' 
      @share.save
      redirect_to shares_path
    end
  end

  def reply
    @share = Share.find(params[:id])

    @reply = Reply.new
    @reply.repliable = @share
    @reply.floor = @share.replies.count + 1
    @reply.user_id = current_user.id
    @reply.content = params[:reply][:content]
    @reply.save

    @share.last_reply_id = current_user.id
    @share.last_reply_user_name = @user.username
    @share.save

    redirect_to share_path(@share)
  end

  def fav
    @share = Share.find(params[:id])

    favorite = Fav.new
    favorite.share_id = @share.id
    favorite.user_id = current_user.id
    favorite.save

    redirect_to share_path(@share.id)
    render :status => 200
  end

  def unfav
    @share = Share.find(params[:id])

    favorite = Fav.where(:user_id => current_user.id, :share_id => @share.id).first
    favorite.delete
    render :status => 200
  end

  def thanks
    @share = Share.find(params[:id])
    @share.rate += 5
    @share.save
    
    render :status => 200
  end

  def ban
    if @user.blank? || @user.state != 'admin'
      redirect_to '/'
      return
    end

    @share = Share.find(params[:share_id])
    @share.state = 'ban'
    @share.save

    render :status => 200
  end
end

app/helpers/share_helper.rb
module ShareHelper
end

app/views/share/edit.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">编辑分享</span>
    </div>
    <div class="ui-content">
        <%= form_for(@share, :class => 'mt10', :url => edit_share_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <%= f.file_field :file %>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/share/index.html.erb
<div class="topics container-box">
  <div class="ui-header">
    <%= link_to '分享新文件', new_share_path('all'), :class => 'btn btn-small fr' %>
    <span class="bread-nav"> 分享 </span>
  </div>

  <% @shares.each do |share| %>
  <div class="topic-item">

    <div class="main">
      <h3 class="title">
        <%= link_to share.title, news_path(share.id) %>
      </h3>

      <div class="ui-content">
        <p><%= share.content %></p>
      </div>

      <div class="meta">
        <span class="username">
          <%= link_to share.user.username, user_path(share.user)  %>
        </span> •
        <span class="last-touched"><%= time_ago_in_words share.created_at %></span> •
      </div>
    </div>
    <div class="count">
      <%= link_to share.replies.count, news_path(share.id) %>
    </div>
  </div>
  <% end %>
</div>

app/views/share/new.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">分享新文件</span>
    </div>
    <div class="ui-content">
        <%= form_for(@share, :class => 'mt10', :url => new_share_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <%= f.file_field :file %>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <%= hidden_field_tag(:node, @nodename) %>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/share/node.html.erb
<div class="topics container-box node-topics">
    <div class="ui-header">
    	<%= link_to '创建新主题', new_share_path(@nodename), :class => 'btn btn-small fr' %>
        <span class="bread-nav"><%= @nodename %></span>
    </div>

    <div class="ui-content">
        <%= render 'layouts/tlist' %>
    </div>

    <% # will_paginate @topics %>
</div>

app/views/share/search.html.erb
<h1>Share#search</h1>
<p>Find me in app/views/share/search.html.erb</p>

app/views/share/show.html.erb
<div class="topic-detail container-box">
<div class="ui-header">
    <%= link_to image_tag(@share.user.avatar, :class => 'avatar'), user_path(@share.user) %>
    <div class="main">
        <h3 class="title"><%= @share.title %></h3>
        <div class="meta">
            <span class="node"><%= link_to @share.node, node_path(@share.node) %></span>
            • <span class="username"><%= link_to @share.user.username, user_path(@share.user.username) %></span>
            • <span class="created-time"><%= time_ago_in_words @share.created_at %></span>
            <% if @share.last_reply_id %>
            • <span class="last-reply-username">最后回复来自 <strong><%= link_to @share.last_reply_user_name, user_path(@share.last_reply_id) %></strong></span>
            <% end %>
        </div>
    </div>
</div>
<div class="ui-content">
    <p><%= @share.content %></p>
</div>
<div class="ui-footer">
    <%= link_to '编辑', edit_share_path(@share.id), :class => 'J_topicVote' %>
    <%= link_to '收藏', fav_path(@share.id), :class => 'J_topicVote' %>
    <%= link_to '喜欢', like_path(@share.id), :class => 'J_topicVote' %>
    <%= link_to '不喜欢', dislike_path(@share.id), :class => 'J_topicVote' %>
    <%= link_to '下载', @share.file.url, :class => 'J_topicVote' %>
    <% if current_user && current_user.state = 'admin' %>
    <%= link_to '屏蔽', ban_path(@share.id), :class => 'J_topicVote' %>
    <% end %>
    <span class="hits fr mr10"><%= @share.page_view %> 次点击</span>
</div>
</div>
<div class="topic-reply container-box">
<div class="ui-header">
    <span>共收到<%= @share.replies.count %>条回复</span>
</div>
<div class="ui-content">
    <%= render :partial => 'layouts/replies', :locals => {:replies => @share.replies} %>
</div>
<div class="ui-footer">
    <div class="pagination pagination-mini"></div>
</div>
</div>


<%= render :partial => 'layouts/reply', :locals => {:url => reply_share_path(@share), :owner_name => :share_id, :owner => @share.id} %>