config/routes.rb
Social::Application.routes.draw do

  get "gist/index"

  get "gist/new"

  get "gist/edit"

  get "gist/show"

  get "friend/index"

  get "friend/search"

  get "admin/index"

  root :to => 'topics#index'

  match  'node/new/:node' => 'topics#new', :as => :new_topic
  get  'node/:node' => "topics#node", :as => :node

  match  't/:id/edit' => 'topics#edit', :as => :edit_topic
  post 't/:id/reply' => 'topics#reply', :as => :reply
  post 't/:id/fav' => 'topics#fav', :as => :fav
  post 't/:id/unfav' => 'topics#unfav', :as => :unfav
  post 't/:id/like' => 'topics#like', :as => :like
  post 't/:id/dislike' => 'topics#dislike', :as => :dislike
  post 't/:id/ban' => 'topics#ban', :as => :ban
  get  't/:id' => 'topics#show', :as => :topic

  post 'r/:id/like' => 'topics#reply_like', :as => :reply_like
  post 'r/:id/dislike' => 'topics#reply_dislike', :as => :reply_dislike

  get  'news' => "news#index", :as => :all_news
  match  'news/new' => 'news#new', :as => :new_news
  match  'news/:id/edit' => 'news#edit', :as => :edit_news
  post 'news/:id/reply' => 'news#reply', :as => :reply_news
  get  'news/:id' => 'news#show', :as => :news
  
  get  'page' => "page#index", :as => :pages
  match  'page/new' => 'page#new', :as => :new_page
  match  'page/:id/edit' => 'page#edit', :as => :edit_page
  post 'gist/:id/reply' => 'gist#reply', :as => :reply_gist
  get  'page/:id' => 'page#show', :as => :page

  get  'gist' => "gist#index", :as => :gists
  match  'gist/new' => 'gist#new', :as => :new_gist
  match  'gist/:id/edit' => 'gist#edit', :as => :edit_gist
  get  'gist/:id' => 'gist#show', :as => :gist

  get  'asks' => "ask#index", :as => :asks
  match  'ask/new' => 'ask#new', :as => :new_ask
  get  'ask/node/:node' => "ask#node", :as => :ask_node
  match  'ask/:id/edit' => 'ask#edit', :as => :edit_ask
  post 'ask/:id/answer' => 'ask#answer', :as => :answer
  post 'ask/:id/fav' => 'ask#fav', :as => :fav_ask
  post 'ask/:id/unfav' => 'ask#unfav', :as => :unfav_ask
  post 'ask/:id/like' => 'ask#like', :as => :like_answer
  post 'ask/:id/dislike' => 'ask#dislike', :as => :dislike_answer
  get  'ask/:id' => 'ask#show', :as => :ask

  get  'friend/(:user)' => "friend#index", :as => :friends
  get  'friend/search/:user' => "friend#search", :as => :search_friends
  post 'friend/:id/follow' => 'friend#follow', :as => :follow_friend
  post 'friend/:id/unfollow' => 'friend#unfollow', :as => :unfollow_friend
  post 'friend/:id/block' => 'friend#block', :as => :block_friend
  post 'friend/:id/unblock' => 'friend#unblock', :as => :unblock_friend

  get  'share' => "share#index", :as => :shares
  match  'share/new/:node' => 'share#new', :as => :new_share
  get  'share/node/:node' => "share#node", :as => :share_node
  match  'share/:id/edit' => 'share#edit', :as => :edit_share
  post 'share/:id/reply' => 'share#reply', :as => :reply_share
  get  'share/:id' => 'share#show', :as => :share

  get  'users' => 'users#index', :as => :users
  get  'users/city/:city' => 'users#city', :as => :users_by_city
  match  'u/setting' => 'users#setting', :as => :user_setting
  match  'u/avatar' => 'users#avatar', :as => :user_avatar
  get  'u/:id/topics' => 'users#topics', :as => :user_topics
  get  'u/:id/replies' => 'users#replies', :as => :user_replies
  get  'u/:id/favs' => 'users#favs', :as => :user_favs
  get  'u/:id' => 'users#show', :as => :user

  match 'signup_by_weibo' => 'users#signup_by_weibo' , :as => :signup_by_weibo

  devise_for :users ,controllers:{omniauth_callbacks: :authentications}

  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'change_pwd' => 'users#change_pwd', :as => :change_pwd
  match 'forgot_pwd' => 'users#forgot_pwd', :as => :forgot_pwd

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :content, :last_reply_id, :last_reply_user_name, :node,
   :page_view, :replied_at, :rate, :state, :tags, :title, :user_id

  has_many :replies, :as => :repliable
  has_many :favs
  belongs_to :user
  #has_many :users, :through => :favs
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:index, :node, :show]

  def index
    @topics = Topic.where(:state => :normal).all
    # flash[:notice] = "vvvvvv"
  end

  def node
    @nodename = params[:node]
    @topics = Topic.where(:node => @nodename, :state => :normal)
  end

  def new
    @nodename = params[:node]
    if request.post?
      @topic = Topic.create(params[:topic])
      @topic.node = @nodename
      @topic.state = 'normal'
      @topic.user = current_user
      @topic.save
      redirect_to topic_path(@topic)
    else
      @topic = Topic.new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    if request.post?
      @topic.update_attributes(params[:topic])
      redirect_to topic_path(@topic)
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @replies = @topic.replies
    @reply = Reply.new
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.user == @user
      @topic.state = 'destroyed' 
    end
  end

  def reply
    @topic = Topic.find(params[:id])

    @reply = Reply.new
    @reply.repliable = @topic
    @reply.floor = @topic.replies.count + 1
    @reply.user_id = current_user.id
    @reply.content = params[:reply][:content]
    @reply.save

    @topic.last_reply_id = current_user.id
    @topic.last_reply_user_name = current_user.username
    @topic.save

    redirect_to topic_path(@topic)
  end

  def fav
    @topic = Topic.find(params[:id])

    favorite = Fav.new
    favorite.topic_id = @topic.id
    favorite.user_id = current_user.id
    favorite.save

    redirect_to topic_path(@topic.id)
    render :status => 200
  end

  def unfav
    @topic = Topic.find(params[:id])

    favorite = Fav.where(:user_id => current_user.id, :topic_id => @topic.id).first
    favorite.delete
    render :status => 200
  end

  def like
    @topic = Topic.find(params[:id])
    @topic.rate += 5
    @topic.save
    
    render :status => 200
  end

  def dislike
    @topic = Topic.find(params[:id])
    @topic.rate -= 5
    @topic.save
    
    render :status => 200
  end

  def ban
    if @user.blank? || @user.state != 'admin'
      redirect_to '/'
      return
    end

    @topic = Topic.find(params[:topic_id])
    @topic.state = 'ban'
    @topic.save

    render :status => 200
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_nodenav.html.erb
<div class="nodes-cloud container-box">
<h4 class="title">节点导航</h4>
<ul>
    <li>
        <label for="">语言</label>
        <span class="nodes">
                <a href="/node/html">HTML</a>
                <a href="/node/css">CSS</a>
                <a href="/node/javascript">JavaScript</a>
                <a href="/node/nodejs">NodeJS</a>
                <a href="/node/ruby">Ruby</a>
                <a href="/node/pyhton">Python</a>
                <a href="/node/php">PHP</a>
        </span>
    </li>
    <li>
        <label for="">分享</label>
        <span class="nodes">
                <a href="/node/opensource">开源项目</a>
                <a href="/node/algorithm">算法</a>
                <a href="/node/math">数学</a>
                <a href="/node/compatibility">兼容性</a>
                <a href="/node/mobile">Mobile</a>
                <a href="/node/books">书籍</a>
                <a href="/node/jobs">招聘</a>
                <a href="/node/share">分享</a>
                <a href="/node/translate">翻译</a>
                <a href="/node/question">问与答</a>
        </span>
    </li>
    <li>
        <label for="">编辑器</label>
        <span class="nodes">
                <a href="/node/sublime">Sublime</a>
                <a href="/node/vim">VIM</a>
                <a href="/node/webstorm">WebStorm</a>
                <a href="/node/notepad">Notepad++</a>
        </span>
    </li>
    <li>
        <label for="">DSL</label>
        <span class="nodes">
                <a href="/node/coffeescript">CoffeeScript</a>
                <a href="/node/sass">Sass</a>
                <a href="/node/less">Less</a>
                <a href="/node/jade">Jade</a>
                <a href="/node/haml">Haml</a>
        </span>
    </li>
    <li>
        <label for="">工具</label>
        <span class="nodes">
                <a href="/node/git">Git</a>
                <a href="/node/nginx">Nginx</a>
                <a href="/node/apache">Apache</a>
        </span>
    </li>
    <li>
        <label for="">框架</label>
        <span class="nodes">
                <a href="/node/jquery">jQuery</a>
                <a href="/node/yui">YUI</a>
                <a href="/node/bootstrap">Bootstrap</a>
                <a href="/node/zepto">Zepto</a>
                <a href="/node/kissy">Kissy</a>
        </span>
    </li>
    <li>
        <label for="">规范</label>
        <span class="nodes">
                <a href="/node/w3c">W3C</a>
                <a href="/node/ecma">ECMA Script</a>
        </span>
    </li>
    <li>
        <label for="">社区</label>
        <span class="nodes">
                <a href="/node/feedback">意见反馈</a>
                <a href="/node/placard">公告</a>
                <a href="/node/dev">社区开发</a>
                <a href="/node/help">帮助</a>
        </span>
    </li>
</ul>
</div>

app/views/topics/_show.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :node_id %><br />
    <%= f.number_field :node_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :pageview %><br />
    <%= f.number_field :pageview %>
  </div>
  <div class="field">
    <%= f.label :reply_count %><br />
    <%= f.number_field :reply_count %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :fav_count %><br />
    <%= f.number_field :fav_count %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">编辑主题</span>
    </div>
    <div class="ui-content">
        <%= form_for(@topic, :class => 'mt10', :url => edit_topic_path(@topic), :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= hidden_field_tag(:node, @nodename) %>
            <%= f.submit "立即保存", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/topics/index.html.erb
<%= render 'layouts/nav' %>

<% if @site && @site.notice %>

<div class=" container-box">
<h4 class="title">公告</h4>
<blockquote  >
	<%= @site.notice %>
</blockquote>
</div>

<% end %>

<!-- list start -->
<div class="topics container-box">
    <%= render 'layouts/tlist' %>
    <% # paginate @topics %>
    <!-- <%= render 'layouts/pagination' %> -->
</div>
<!-- list end -->

app/views/topics/new.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">发表主题</span>
    </div>
    <div class="ui-content">
        <%= form_for(@topic, :class => 'mt10', :url => new_topic_path(@nodename), :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= hidden_field_tag(:node, @nodename) %>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/topics/node.html.erb
<div class="topics container-box node-topics">
    <div class="ui-header">
    	<%= link_to '创建新主题', new_topic_path(@nodename), :class => 'btn btn-small fr' %>
        <span class="bread-nav"><%= @nodename %></span>
    </div>

    <div class="ui-content">
        <%= render 'layouts/tlist' %>
    </div>

    <% # will_paginate @topics %>
</div>

app/views/topics/show.html.erb
<div class="topic-detail container-box">
<div class="ui-header">
    <%= link_to image_tag(@topic.user.avatar, :class => 'avatar'), user_path(@topic.user) %>
    <div class="main">
        <h3 class="title"><%= @topic.title %></h3>
        <div class="meta">
            <span class="node"><%= link_to @topic.node, node_path(@topic.node) %></span>
            • <span class="username"><%= link_to @topic.user.username, user_path(@topic.user.username) %></span>
            • <span class="created-time"><%= time_ago_in_words @topic.created_at %></span>
            <% if @topic.last_reply_id %>
            • <span class="last-reply-username">最后回复来自 <strong><%= link_to @topic.last_reply_user_name, user_path(@topic.last_reply_id) %></strong></span>
            <% end %>
        </div>
    </div>
</div>
<div class="ui-content">
    <p><%= @topic.content %></p>
</div>
<div class="ui-footer">
    <a href="#" onclick="window.open('https://twitter.com/intent/tweet?hashtags=<%= @topic.node %>&amp;text=<%= @topic.title %>&amp;url=<%= topic_url(@topic.id) %>');">Tweet</a>
    <a href="#" onclick="window.open('http://service.weibo.com/share/share.php?url=<%= topic_url(@topic.id) %>&amp;title=<%= @topic.title %>', '_blank', 'width=550, height=370');">新浪微博</a>
    <%= link_to '编辑', edit_topic_path(@topic.id), :class => 'J_topicVote' %>
    <%= link_to '收藏', fav_path(@topic.id), :class => 'J_topicVote' %>
    <%= link_to '喜欢', like_path(@topic.id), :class => 'J_topicVote' %>
    <%= link_to '不喜欢', dislike_path(@topic.id), :class => 'J_topicVote' %>
    <% if @user && @user.state = 'admin' %>
    <%= link_to '屏蔽', ban_path(@topic.id), :class => 'J_topicVote' %>
    <% end %>
    <span class="hits fr mr10"><%= @topic.page_view %> 次点击</span>
</div>
</div>
<div class="topic-reply container-box">
<div class="ui-header">
    <span>共收到<%= @topic.replies.count %>条回复</span>
</div>
<div class="ui-content">
    <%= render :partial => 'layouts/replies', :locals => {:replies => @topic.replies} %>
</div>
<div class="ui-footer">
    <div class="pagination pagination-mini"></div>
</div>
</div>


<%= render :partial => 'layouts/reply', :locals => {:url => reply_path(@topic), :owner_name => :topic_id, :owner => @topic.id} %>