config/routes.rb
Social::Application.routes.draw do

  get "gist/index"

  get "gist/new"

  get "gist/edit"

  get "gist/show"

  get "friend/index"

  get "friend/search"

  get "admin/index"

  root :to => 'topics#index'

  match  'node/new/:node' => 'topics#new', :as => :new_topic
  get  'node/:node' => "topics#node", :as => :node

  match  't/:id/edit' => 'topics#edit', :as => :edit_topic
  post 't/:id/reply' => 'topics#reply', :as => :reply
  post 't/:id/fav' => 'topics#fav', :as => :fav
  post 't/:id/unfav' => 'topics#unfav', :as => :unfav
  post 't/:id/like' => 'topics#like', :as => :like
  post 't/:id/dislike' => 'topics#dislike', :as => :dislike
  post 't/:id/ban' => 'topics#ban', :as => :ban
  get  't/:id' => 'topics#show', :as => :topic

  post 'r/:id/like' => 'topics#reply_like', :as => :reply_like
  post 'r/:id/dislike' => 'topics#reply_dislike', :as => :reply_dislike

  get  'news' => "news#index", :as => :all_news
  match  'news/new' => 'news#new', :as => :new_news
  match  'news/:id/edit' => 'news#edit', :as => :edit_news
  post 'news/:id/reply' => 'news#reply', :as => :reply_news
  get  'news/:id' => 'news#show', :as => :news
  
  get  'page' => "page#index", :as => :pages
  match  'page/new' => 'page#new', :as => :new_page
  match  'page/:id/edit' => 'page#edit', :as => :edit_page
  post 'gist/:id/reply' => 'gist#reply', :as => :reply_gist
  get  'page/:id' => 'page#show', :as => :page

  get  'gist' => "gist#index", :as => :gists
  match  'gist/new' => 'gist#new', :as => :new_gist
  match  'gist/:id/edit' => 'gist#edit', :as => :edit_gist
  get  'gist/:id' => 'gist#show', :as => :gist

  get  'asks' => "ask#index", :as => :asks
  match  'ask/new' => 'ask#new', :as => :new_ask
  get  'ask/node/:node' => "ask#node", :as => :ask_node
  match  'ask/:id/edit' => 'ask#edit', :as => :edit_ask
  post 'ask/:id/answer' => 'ask#answer', :as => :answer
  post 'ask/:id/fav' => 'ask#fav', :as => :fav_ask
  post 'ask/:id/unfav' => 'ask#unfav', :as => :unfav_ask
  post 'ask/:id/like' => 'ask#like', :as => :like_answer
  post 'ask/:id/dislike' => 'ask#dislike', :as => :dislike_answer
  get  'ask/:id' => 'ask#show', :as => :ask

  get  'friend/(:user)' => "friend#index", :as => :friends
  get  'friend/search/:user' => "friend#search", :as => :search_friends
  post 'friend/:id/follow' => 'friend#follow', :as => :follow_friend
  post 'friend/:id/unfollow' => 'friend#unfollow', :as => :unfollow_friend
  post 'friend/:id/block' => 'friend#block', :as => :block_friend
  post 'friend/:id/unblock' => 'friend#unblock', :as => :unblock_friend

  get  'share' => "share#index", :as => :shares
  match  'share/new/:node' => 'share#new', :as => :new_share
  get  'share/node/:node' => "share#node", :as => :share_node
  match  'share/:id/edit' => 'share#edit', :as => :edit_share
  post 'share/:id/reply' => 'share#reply', :as => :reply_share
  get  'share/:id' => 'share#show', :as => :share

  get  'users' => 'users#index', :as => :users
  get  'users/city/:city' => 'users#city', :as => :users_by_city
  match  'u/setting' => 'users#setting', :as => :user_setting
  match  'u/avatar' => 'users#avatar', :as => :user_avatar
  get  'u/:id/topics' => 'users#topics', :as => :user_topics
  get  'u/:id/replies' => 'users#replies', :as => :user_replies
  get  'u/:id/favs' => 'users#favs', :as => :user_favs
  get  'u/:id' => 'users#show', :as => :user

  match 'signup_by_weibo' => 'users#signup_by_weibo' , :as => :signup_by_weibo

  devise_for :users ,controllers:{omniauth_callbacks: :authentications}

  match 'login' => 'users#login', :as => :login
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'change_pwd' => 'users#change_pwd', :as => :change_pwd
  match 'forgot_pwd' => 'users#forgot_pwd', :as => :forgot_pwd

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :question_id, :rate, :state, :user_id, :floor
  belongs_to :user
  belongs_to :question
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :page_view, :rate, :state, :tags, :title, :user_id
  belongs_to :user
  has_many :replies, :as => :repliable
end

app/models/fav.rb
class Fav < ActiveRecord::Base
  attr_accessible :kind, :topic_id, :user_id
  belongs_to :topics
  belongs_to :users
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :owner_id, :target_id
end

app/models/gist.rb
class Gist < ActiveRecord::Base
  attr_accessible :content, :description, :title, :user_id
  has_many :replies, :as => :repliable
  belongs_to :user
end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :kind, :sort, :summary, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title, :url
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :state, :rate, :title, :content, :page_view, :tags, :replied_at, :selected_id, :due_date, :user_id
  belongs_to :user
  has_many :answers
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :content, :rate, :state, :owner_id, :user_id, :floor, :repliable
  belongs_to :user
  belongs_to :repliable, :polymorphic => true
end

app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :content, :last_reply_id, :last_reply_user_name, :node,
   :page_view, :replied_at, :rate, :state, :tags, :title, :user_id,
   :download_count, :file
   has_many :replies, :as => :repliable
   belongs_to :user
   has_attached_file :file
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :ad, :config, :hot_node, :intro, :logo, :nav, :node_count, :notice,
   :reply_count, :state, :title, :top_topic_id, :topic_count, :url, :user_count
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :content, :last_reply_id, :last_reply_user_name, :node,
   :page_view, :replied_at, :rate, :state, :tags, :title, :user_id

  has_many :replies, :as => :repliable
  has_many :favs
  belongs_to :user
  #has_many :users, :through => :favs
end

app/models/user.rb
class User < ActiveRecord::Base  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable,# :confirmable,
         :lockable, :timeoutable, :omniauthable,omniauth_providers: [:weibo]

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :username, :saying, :sex, :location, :avatar, :rate, :state
  
  has_attached_file :avatar, :default_url => "/images/missing.png"

  has_many :topics
  has_many :replies
  has_many :favs
  has_many :shares

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ask_helper.rb
module AskHelper
end

app/helpers/gist_helper.rb
module GistHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/share_helper.rb
module ShareHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="span9">

<!-- settings start -->
<div class="container-box">
<form class="form-horizontal" action="" method="POST">
    <fieldset>
        <div id="legend">
            <legend class="">网站管理</legend>
        </div>


        <div class="control-group">
            <!-- Nickname -->
            <label class="control-label" for="title">网站名称</label>

            <div class="controls">
                <input id="title" name="title" placeholder="" class="input-xlarge" value="<%= @site.title %>" type="text">

                <p class="help-block">请输入网站的名称</p>
            </div>
        </div>

        <div class="control-group">
            <!-- Nickname -->
            <label class="control-label" for="logo">logo url</label>

            <div class="controls">
                <input id="logo" name="logo" placeholder="" class="input-xlarge" value="<%= @site.logo %>" type="text">

                <p class="help-block">请输入网站logo的url</p>
            </div>
        </div>

        <div class="control-group">
            <!-- Nickname -->
            <label class="control-label" for="notice">公告</label>

            <div class="controls">
                <input id="nickname" name="notice" placeholder="" class="input-xlarge" value="<%= @site.ad %>" type="text">

                <p class="help-block">请输入网站的公告</p>
            </div>
        </div>



        <div class="control-group">
            <!-- E-mail -->
            <label class="control-label" for="hot_node">编辑热门节点</label>

            <div class="controls">
                <textarea type="text" id="hot_node" name="hot_node" value="<%= @site.hot_node %>"
                          class="input-xlarge"></textarea>
            </div>
        </div>

        <div class="control-group">
            <!-- E-mail -->
            <label class="control-label" for="top_topic">编辑置顶话题</label>

            <div class="controls">
                <textarea type="text" id="top_topic" name="top_topic" value="<%= @site.top_topic %>"
                          class="input-xlarge"></textarea>
            </div>
        </div>

        <div class="control-group">
            <!-- E-mail -->
            <label class="control-label" for="ad">编辑广告内容</label>

            <div class="controls">
                <textarea type="text" id="ad" name="ad" value="<%= @site.ad %>"
                          class="input-xlarge"></textarea>
            </div>
        </div>

        <div class="control-group">
            <!-- E-mail -->
            <label class="control-label" for="state">设置网站状态</label>

            <div class="controls">
                <select id="state" name="state" value="<%= @site.state %>" class="input-xlarge">
                  <option>normal</option>
                  <option>closed</option>
                </select>
            </div>
        </div>



        <div class="control-group">
            <!-- Button -->
            <div class="controls">
                <button class="btn btn-success">保存改动</button>
            </div>
        </div>
    </fieldset>
</form>
</div>
<!-- settings end -->

</div>

app/views/layouts/_nav.html.erb
<div class="nodes-cloud container-box">
<h4 class="title">导航</h4>

<ul>
    <li>
        <label for="">技术</label>
        <span class="nodes">
                <a href="/node/ruby">Ruby</a>
                <a href="/node/pyhton">Python</a>
                <a href="/node/php">PHP</a>
                <a href="/node/html">HTML</a>
                <a href="/node/css">CSS</a>
                <a href="/node/javascript">JavaScript</a>
                <a href="/node/nodejs">NodeJS</a>
        </span>
    </li>
    <li>
        <label for="">科学</label>
        <span class="nodes">
                <a href="/node/xxx">数学</a>
                <a href="/node/xxx">物理</a>
                <a href="/node/xxx">语文</a>
                <a href="/node/xxx">地理</a>
                <a href="/node/xxx">天文</a>
                <a href="/node/xxx">生物</a>
                <a href="/node/xxx">海洋学</a>
        </span>
    </li>
    <li>
        <label for="">文化</label>
        <span class="nodes">
                <a href="/node/literal">文学</a>
                <a href="/node/movie">电影</a>
                <a href="/node/music">音乐</a>
        </span>
    </li>
</ul>
</div>

app/views/layouts/_pagination.html.erb
<div class="pagination hide">
    <ul>
        <li class="disabled"><a href="/?p=1">«</a></li>
        <li class="active"><a href="javascript:;">1</a></li>
        <li><a href="/?p=2">2</a></li>
        <li><a href="/?p=3">3</a></li>
        <li><a href="/?p=4">4</a></li>
        <li><a href="/?p=2">»</a></li>
    </ul>
</div>

app/views/layouts/_replies.html.erb
<!-- nice -->
<% replies.each do |reply| %>
<div class="reply-item">
  <%= link_to image_tag(reply.user.avatar, :class => 'avatar'), user_path(reply.user) %>
  <div class="main">
    <div class="meta">
      <a href="<%= user_path(reply.user) %>" class="reply-username">
        <span class="username"><%= reply.user.username %></span>
      </a>
      <span class="time"><%= time_ago_in_words reply.created_at %></span>
      <a href="<%= reply_like_path(reply.id) %>" class="J_topicVote">感谢</a>
      <span class="floor fr">#<%= reply.floor %></span>
      <span class="reply-to fr J_replyTo" data-username="<%= reply.user.username %>">
        <img src="/reply.png" alt="">
      </span>
    </div>
    <span class="content"><p><%= reply.content %></p></span>
  </div>
</div>
<% end %>

app/views/layouts/_reply.html.erb
<!-- nice -->
<% if user_signed_in? %>
<div class="topic-reply-create container-box">
<div class="ui-header">
  <span class="title">创建新的回复</span>
</div>
<div class="ui-content">
  <%= form_for(@reply, :class => 'mt10', :url => url, :method => :post) do |f| %>
    <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '回复内容' %>
    <%= hidden_field_tag(owner_name, owner) %>
    <%= f.submit "立即回复", :class => 'btn btn-small' %>
  <% end %>
</div>
</div>
<% end %>

app/views/layouts/_rlist.html.erb
    <% counter = 0 %>
    <% @topic.replies.each do |reply| %>
    <div class="reply-item">
        <a href="/u/guokai">
            <img src="<%= reply.user.avatar %>"
                 alt="" class="avatar">
        </a>

        <div class="main">
            <div class="meta">
                <a href="/u/guokai" class="reply-username">
                    <span class="username"><%= reply.user.username %></span>
                </a>
                <span class="time"><%= time_ago_in_words reply.created_at %></span>
                <a href="<%= thanks_path(@topic.id) %>" class="J_topicVote">感谢</a>
                <span class="floor fr">#<%= counter+=1 %></span>
                <span class="reply-to fr J_replyTo" data-username="<%= reply.user.username %>">
                    <img src="/reply.png" alt="">
                </span>
            </div>
            <span class="content"><p><%= reply.content %></p></span>
        </div>
    </div>
    <% end %>

app/views/layouts/_sidebar.html.erb
<div class="span3">

  <% if current_user %>

  <div class="usercard container-box">
      <div class="ui-header">
          <a href="<%= user_path current_user %>">
            <%= image_tag current_user.avatar, :class => 'avatar' %>
          </a>

          <div class="username"><%= current_user.username %></div>
          <div class="website"><a href=""></a></div>
      </div>
      <div class="ui-content">
          <div class="status status-topic">
              <strong><%= link_to current_user.topics.count, user_topics_path(current_user) %></strong> 主题
          </div>
          <div class="status status-reply">
              <strong><%= link_to current_user.replies.count, user_replies_path(current_user) %></strong> 回复
          </div>
          <div class="status status-favorite">
              <strong><%= link_to current_user.favs.count, user_favs_path(current_user) %></strong> 收藏
          </div>
          <div class="status status-reputation">
              <strong><%= current_user.rate %></strong> 金币
          </div>
      </div>
  </div>

  <% else %>

  <div class="login-box container-box">
      <div class="ui-content tc">
        <%= link_to '注册', new_user_registration_path, :class => 'btn btn-small' %>
        <%= link_to '登录', new_user_session_path, :class => 'btn btn-small' %>
      </div>
  </div>

  <% end %>

  <!-- 

  <div class="sidebox container-box">
      <div class="ui-header">
          <span class="title">微信公共帐号</span>
      </div>
      <div class="ui-content">
          <img src="/qrrrrrrrcode.jpg" alt="">
      </div>
  </div>

  -->


  <div class="sidebox container-box hot-nodes">
      <div class="ui-header">
          <span class="title">最热节点</span>
      </div>
      <div class="ui-content">
                <a href="/node/xxx">数学</a>
                <a href="/node/xxx">物理</a>
                <a href="/node/xxx">语文</a>
                <a href="/node/xxx">地理</a>
                <a href="/node/xxx">天文</a>
                <a href="/node/xxx">生物</a>
                <a href="/node/xxx">海洋学</a>
      </div>
  </div>

  <div class="sidebox container-box community-status">
      <div class="ui-header">
          <span class="title">运行状态</span>
      </div>
      <div class="ui-content">
          <dl>
              <dt>注册成员</dt>
              <dd><%= @site.user_count %></dd>
          </dl>
          <dl>
              <dt>节点</dt>
              <dd><%= @site.node_count %></dd>
          </dl>
          <dl>
              <dt>主题</dt>
              <dd><%= @site.topic_count %></dd>
          </dl>
          <dl>
              <dt>回复</dt>
              <dd><%= @site.reply_count %></dd>
          </dl>
      </div>
  </div>

</div>

app/views/layouts/_tlist.html.erb
<% @topics.each do |topic| %>
<div class="topic-item">
    <%= link_to image_tag(topic.user.avatar, :class => 'avatar'), user_path(topic.user) %>

    <div class="main">
        <h3 class="title">
            <%= link_to topic.title, topic_path(topic.id, :anchor => "reply#{topic.replies.count}") %>
        </h3>

        <div class="meta">
            <span class="node"><%= link_to topic.node, node_path(topic.node) %></span> •
            <span class="username">
                <%= link_to topic.user.username, user_path(topic.user)  %>
            </span> •
            <span class="last-touched"><%= time_ago_in_words topic.created_at %></span> •
            <% if topic.last_reply_id %>
            <span class="last-reply-username">最后回复来自 <strong><%= link_to topic.last_reply_user_name, user_path(topic.last_reply_id) %></strong></span>
            <% end %>
        </div>
    </div>
    <div class="count">
        <%= link_to topic.replies.count, topic_path(topic.id) %>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Social</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <link href="/f2e.css" rel="stylesheet">
    <link href="/campo.css" rel="stylesheet">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="/assets/ico/favicon.png">
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/"><%= @site.title %></a>
            <div class="nav-collapse collapse">
            
                <ul class="nav">
                        <li class="active"><%= link_to '社区', root_path %></li>
                        <li><%= link_to '新闻', all_news_path %></li>
                        <li><%= link_to '资源', shares_path %></li>
                        <li><%= link_to '成员', users_path %></li>
                        <li><%= link_to '问答', asks_path %></li>
                        <li><%= link_to '笔记', gists_path %></li>
                        <li><%= link_to '页面', pages_path %></li>
                        <li><%= link_to '好友', friends_path %></li>
                        <li><a class="hide" href="/admin">管理</a></li>
                        <% if current_user && current_user.state == 'admin' %>
                        <% end %>
                </ul>
            </div>
            <form class="navbar-search pull-left J_search">
                <input type="text" class="search-query" placeholder="Search" x-webkit-speech="">
            </form>
            <div class="nav-collapse collapse pull-right">
                <ul class="nav">
                    <% if current_user %>
                    <li><%= link_to current_user.username, user_setting_path %></li>
                    <li><a href="/logout">退出</a></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="content" class="container">

    <div class="row">

        <div id="main" class="span9">

        <% if flash[:omniauth] %>
        <div class=" container-box">
        <h4 class="title">公告</h4>
        <blockquote  >
            <%= flash[:omniauth] %>
        </blockquote>
        </div>
        <% end %>

        <%= yield %>
        </div>

        <%= render 'layouts/sidebar' %>

    </div>

</div>

<div class="footer mt15" style="margin-top: 15px;">
    <div class="container">
        <div class="footer-bg">
            <p class="links">
                <span>©2012-2013 </span>
                <span>Powered by Jiang</span>
            </p>
            <p class="fade-color">
                <span># version 0.5.0</span>
            </p>
        </div>
    </div>
</div>
<script src="/assets/js/jquery.js"></script>
<script src="/assets/js/bootstrap-transition.js"></script>
<script src="/assets/js/bootstrap-alert.js"></script>
<script src="/assets/js/bootstrap-modal.js"></script>
<script src="/assets/js/bootstrap-dropdown.js"></script>
<script src="/assets/js/bootstrap-scrollspy.js"></script>
<script src="/assets/js/bootstrap-tab.js"></script>
<script src="/assets/js/bootstrap-tooltip.js"></script>
<script src="/assets/js/bootstrap-popover.js"></script>
<script src="/assets/js/bootstrap-button.js"></script>
<script src="/assets/js/bootstrap-collapse.js"></script>
<script src="/assets/js/bootstrap-carousel.js"></script>
<script src="/assets/js/bootstrap-typeahead.js"></script>
<script src="/campo.js"></script>

</body>
</html>

app/views/page/edit.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">编辑</span>
    </div>
    <div class="ui-content">
        <%= form_for(@page, :class => 'mt10', :url => edit_page_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/page/index.html.erb
<div class="topics container-box">
  <div class="ui-header">
    <%= link_to '创建新页面', new_page_path, :class => 'btn btn-small fr' %>
    <span class="bread-nav"> 页面 </span>
  </div>

  <% @pages.each do |page| %>
  <div class="topic-item">

    <div class="main">
      <h3 class="title">
        <%= link_to page.title, page_path(page.id) %>
      </h3>

      <div class="meta">
        <span class="last-touched"><%= time_ago_in_words page.created_at %></span> •
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/page/new.html.erb
<div class="topic-create container-box">
    <div class="ui-header">
        <span class="title">发表页面</span>
    </div>
    <div class="ui-content">
        <%= form_for(@page, :class => 'mt10', :url => new_page_path, :method => :post) do |f| %>
            <div class="input-prepend mt10">
                <span class="add-on">#</span>
                <%= f.text_field :title, :autofocus => true, :class => 'span8', :placeholder => '主题' %>
            </div>
            <div id="editor-button-bar"></div>
            <%= f.text_area :content, :autofocus => true, :class => 'content mt5 smart-code-support', :rows => 3, :placeholder => '正文' %>
            <div id="editor-preview"></div>
            <%= f.submit "立即发布", :class => 'btn btn-small' %>
        <% end %>
    </div>
</div>

app/views/page/show.html.erb
<div class="topic-detail container-box">
<div class="ui-header">
    <div class="main">
        <h3 class="title"><%= @page.title %></h3>
        <div class="meta">
            • <span class="created-time"><%= time_ago_in_words @page.created_at %></span>
        </div>
    </div>
</div>
<div class="ui-content">
    <p><%= @page.content %></p>
</div>
<div class="ui-footer">
    <%= link_to '编辑', edit_page_path(@page.id), :class => 'J_topicVote' %>
</div>
</div>